### ISSUE TITLE
Fail to login after server up for long time

### ISSUE THREAD

**Issue by thcathy** [TravisLi/mastery-back-end#1]
mastery-back-end_1  | 2017-08-21 19:58:22.645 m.schooltracs.core.SchoolTracsAgent - Search Customer by Phone Start
mastery-back-end_1  | 2017-08-21 19:58:22.653 m.schooltracs.core.SchoolTracsConn - Send Customer Request
mastery-back-end_1  | 2017-08-21 19:58:23.248 m.schooltracs.core.SchoolTracsAgent - Json=
mastery-back-end_1  | 2017-08-21 19:58:23.251 m.schooltracs.core.SchoolTracsAgent - No content to map due to end-of-input
mastery-back-end_1  |  at [Source: ; line: 1, column: 0]
mastery-back-end_1  | com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
mastery-back-end_1  |  at [Source: ; line: 1, column: 0]
mastery-back-end_1  | 	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
mastery-back-end_1  | 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3838)
mastery-back-end_1  | 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
mastery-back-end_1  | 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2880)
mastery-back-end_1  | 	at mastery.schooltracs.core.SchoolTracsAgent.jsonToCusts(SchoolTracsAgent.java:463)
mastery-back-end_1  | 	at mastery.schooltracs.core.SchoolTracsAgent.schCustsByPhone(SchoolTracsAgent.java:100)
mastery-back-end_1  | 	at mastery.controller.RestApiController.login(RestApiController.java:43)
mastery-back-end_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
mastery-back-end_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
mastery-back-end_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mastery-back-end_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
mastery-back-end_1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)
mastery-back-end_1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
mastery-back-end_1  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
mastery-back-end_1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
mastery-back-end_1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
mastery-back-end_1  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
mastery-back-end_1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
mastery-back-end_1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
mastery-back-end_1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
mastery-back-end_1  | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
mastery-back-end_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
mastery-back-end_1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
mastery-back-end_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
mastery-back-end_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
mastery-back-end_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
mastery-back-end_1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
mastery-back-end_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
mastery-back-end_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
mastery-back-end_1  | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
mastery-back-end_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
mastery-back-end_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
mastery-back-end_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
mastery-back-end_1  | 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89)
mastery-back-end_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
mastery-back-end_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
mastery-back-end_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
mastery-back-end_1  | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
mastery-back-end_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
mastery-back-end_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
mastery-back-end_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
mastery-back-end_1  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
mastery-back-end_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
mastery-back-end_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
mastery-back-end_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
mastery-back-end_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
mastery-back-end_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
mastery-back-end_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
mastery-back-end_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
mastery-back-end_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
mastery-back-end_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
mastery-back-end_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
mastery-back-end_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
mastery-back-end_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
mastery-back-end_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
mastery-back-end_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
mastery-back-end_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
mastery-back-end_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
mastery-back-end_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
mastery-back-end_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
mastery-back-end_1  | 	at java.lang.Thread.run(Thread.java:745)

**Comment by thcathy** [comment]
I found that restart always works

**Comment by TravisLi** [comment]
An action observer to handle re-login to schooltracs if idle for 60 mins and re-login to schooltracs if its response is empty according to your given log. Please test again
